---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/movies/search/{title}":
    get:
      summary: Search movies by Title into OMDB API
      tags:
      - Movies
      parameters:
      - name: title
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: search result
  "/movies/{imdb_id}":
    get:
      summary: Retrieves a Movie by its IMDB ID
      tags:
      - Movies
      parameters:
      - name: imdb_id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Movie details
  "/notes":
    get:
      summary: List all your personal notes
      tags:
      - Notes
      responses:
        '200':
          description: Personal notes list
    post:
      summary: Creates a new Personal Note
      tags:
      - Notes
      parameters: []
      responses:
        '200':
          description: Personal Note created
        '401':
          description: IMDB ID has already been taken
      requestBody:
        content:
          application/json:
            schema:
              type: string
            examples:
              unwatched_movie_save:
                summary: A default save to local Notes as Unwatched
                value:
                  imdb_id: tt0126029
                  title: Shrek
                  watched: false
                  raiting:
                  comment:
        required: true
  "/notes/{imdb_id}":
    put:
      summary: Updates a personal Note
      tags:
      - Notes
      parameters:
      - name: imdb_id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Movie details
      requestBody:
        content:
          application/json:
            schema:
              type: boolean
            examples:
              5_stars_comment:
                summary: 5 Stars Comment
                value:
                  watched: true
                  raiting: 5
                  comment: Excelent movie!
servers:
- url: http://localhost:3000
  variables:
    defaultHost:
      default: http://localhost:3000
